### ISSUE TITLE
On-screen keyboard and its settings doesn't work

### ISSUE THREAD

**Issue by welaq** [elementary/switchboard-plug-a11y#37]
On Juno Beta when I turn on on-screen keyboard nothing happens. When I click on "On-screen keyboard settings..." nothing happens.

**Comment by leonardo-lemos** [comment]
It seems that Onboard is not included in the ISO.

**Comment by arshubham** [comment]
I reported this bug a few days back https://github.com/elementary/switchboard-plug-a11y/issues/34 however due to onboard crashes the fix was backed out.

**Comment by codygarver** [comment]
Duplicate of reopened #34
