### ISSUE TITLE
Universal Access not in System Settings

### ISSUE THREAD

**Issue by benggarza** [elementary/switchboard-plug-a11y#45]
I'm not sure how it happened, but when I open System Settings, there is no Universal Access icon. I tried restoring default settings, but it did not work.
![screenshot from 2018-11-16 19-49-35](https://user-images.githubusercontent.com/44279732/48656328-cc06b700-e9d8-11e8-83ab-50a1901e6804.png)

**Comment by cassidyjames** [comment]
It looks like it may have gotten uninstalled. Can you try opening a Terminal and running `sudo apt install switchboard-plug-a11y`?

**Comment by benggarza** [comment]
That did the trick, thanks!
