### ISSUE TITLE
Changing reading text size does not change things universally

### ISSUE THREAD

**Issue by KeironO** [elementary/switchboard-plug-a11y#49]
I'm afraid that changing text size via Universal Access does not make the changes system-wide.

Bitwarden AppImage against Epiphany.

![BitWarden AppImage](https://i.imgur.com/IYb2Bz7.png)

GNOME System Settings installed via ```apt``` against Epiphany

![GNOMME System Settings](https://i.imgur.com/xRXxWjo.png)

**Comment by cassidyjames** [comment]
We are setting the correct key from the accessibility settings. If other apps don't respect it, that is a bug in those apps and cannot be solved here.
