### ISSUE TITLE
High contrast theme heavily breaks styles

### ISSUE THREAD

**Issue by Exalm** [elementary/switchboard-plug-a11y#50]
Toggling high contrast theme enables upstream Adwaita-like HighContrast theme and icons, which looks pretty broken on elementary: everything has wrong size, missing icons, etc.

![Screenshot from 2019-05-28 20-44-02](https://user-images.githubusercontent.com/1510457/58492472-7ddd2800-8160-11e9-985c-ec0d691027b1.png)

**Comment by danrabbit** [comment]
Since the default stylesheet now aims to achieve at least WCAG AA and considering that this makes the UI more illegible, we should probably remove this option.
