### ISSUE TITLE
Wrong or missing links to source in Weblate platfrom strings

### ISSUE THREAD

**Issue by comradekingu** [elementary/switchboard-plug-a11y#55]
https://l10n.elementary.io/translate/switchboard/universal-access-plug-extra/nb/?checksum=8cc1dc6c7a29dd63

links to
https://github.com/elementary/switchboard-plug-a11y/blob/master//data/io.elementary.switchboard-plug-a11y.appdata.xml.in#L5
whereas it should be
https://github.com/elementary/switchboard-plug-a11y/blob/master/data/io.elementary.switchboard.a11y.appdata.xml.in#L5

The difference is
https://github.com/elementary/switchboard-plug-a11y/blob/master 

> /

 /data/io.elementary.switchboard

> -plug-

a11y.appdata.xml.in#L5

Same for other (extra) components in Switchboard

The error is in the [info setup](https://l10n.elementary.io/projects/switchboard/universal-access-plug-extra/#information):
![bilde](https://user-images.githubusercontent.com/13802408/60143914-cc61fe80-97c0-11e9-93c0-79528c61c790.png)

https://l10n.elementary.io/translate/desktop/feedback-extra/nb/?checksum=c6fa14d8af7c2efb

---

![bilde](https://user-images.githubusercontent.com/13802408/60144079-632ebb00-97c1-11e9-8032-c7768614493e.png)

Is missing a .git extension in its [info section](https://l10n.elementary.io/projects/desktop/feedback-extra/#information)
[
My user](https://l10n.elementary.io/user/kingu/) is not an admin, but I could fix things like this, upload screenshots and add weighting to the strings if it was.

**Comment by ryonakano** [comment]
Fixed. Thank you for your reporting!
