### ISSUE TITLE
Add a switch to toggle visibility of a11y indicator

### ISSUE THREAD

**Issue by ryonakano** [elementary/switchboard-plug-a11y#66]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
It looks like there's no switch to show/hide Wingpanel Universal Access Indicator in System Settings.

**Describe the solution you'd like**
We may want to add a switch to toggle the GSettings key `org.gnome.desktop.a11y always-show-universal-access-status` which Wingpanel Universal Access Indicator uses to toggle its visibility.

**Comment by danrabbit** [comment]
I think we should probably not rely on the GNOME key here and create our own key with the indicator. This way we can test for its existence and make sure we're actually toggling the visibility of our specific indicator

**Comment by ryonakano** [comment]
Where is an appropriate pane to show this switch? I thought General pane but it's already removed in the latest master branch…
