### ISSUE TITLE
New update removes parts of the "universal access" in settings

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/switchboard-plug-a11y#70]
The system, as usual, gave me a notification about new updates. Opened AppCenter and took the updates. Rebooted, went back into settings/universal access to find "General" and "display" sections gone. Therefore, I wasn't able to toggle "Panel transparency" or "high contrast theme" on or off nor was I able to change the text size. I have timeshift installed and had to restore back to a previous backup. Unfortunately, I don't know how to pull the exact build number that I am on nor the new update build number(if there are such thing) to be more exact on this reporting. If there is a way to pull such things, please let me know and I will get the info.
here is my neofetch for more info on the system:
 
OS: elementary OS 5.1.2 Hera x86_64 
Host: Inspiron 7573 
Kernel: 5.3.0-45-generic 
Uptime: 2 hours, 46 mins 
Packages: 2244 
Shell: bash 4.4.20 
Resolution: 3200x1800 
 WM: Mutter(Gala) 
Theme: Breeze [GTK2] 
Icons: Breeze [GTK2] 
Terminal: io.elementary.t 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
GPU: NVIDIA GeForce MX130 
Memory: 2151MiB / 15478MiB 

Thank you.

**Comment by kgrubb** [comment]
Panel translucency and text sizes are now under `Settings -> Desktop -> Appearance`:

![Screenshot from 2020-04-02 13 09 56](https://user-images.githubusercontent.com/8471701/78277943-4ad39580-74e3-11ea-85ad-9b0121175388.png)


I'm not sure where the high contrast theme setting is, though.

**Comment by cassidyjames** [comment]
@KarkanAlzwayed thanks for reporting! All of the settings had previously been moved to their more precise settings pages. For panel transparency and text size, head to _Desktop_ → _Appearance_.

We [wrote about this on our blog](https://blog.elementary.io/accessibility-features-are-just-features/) over a year ago, and I gave [a related talk](https://cassidyjames.com/talks/curb-cuts/) at the Linux App Summit this past fall.

The one exception is the "high contrast theme" which has always been buggy and poorly supported; it didn't ever support elementary APIs or widgets, and in many cases, it would break apps and make them unusable. For the time being, our goal is for the standard elementary stylesheet to be contrast-compliant—and it has improved substantially over the past months. In the future, a high contrast filter at the window manager level might be more appropriate, and is something that has been brought up by GNOME developers as well. An advantage of that approach would be that even non-native apps would be included.

**Comment by cassidyjames** [comment]
Something I was considering is an infobar informing users of the change, in case they (understandably) don't follow us on social media/blog/etc. It could be something as simple as:

>**Looking for a setting that used to be here?**
>To encourage more accessible settings for everyone, some settings that used to be here have been moved to their relevant settings pages.

**Comment by danrabbit** [comment]
Just to add to this, you can always search for specific settings from the system settings home page or the applications menu. The search is pretty good these days :)

**Comment by KarkanAlzwayed** [comment]
Thank you to all who replied. I'm committed to help make EOS as good as a distro could get because I, 1. Have been a happy user for a long while. 2. Believe in its tremendous potential. 
It has been very solid for me, except for some small issues here and there that I'm trying to compile in one report and deliver it to you guys somehow. I hope that I didn't waste anyone's time with this or future ones. I'll look harder next time.
Thank you.

**Comment by danrabbit** [comment]
I'm going to reopen this issue report since it sounds like some messaging in-app would be useful

**Comment by cassidyjames** [comment]
Workshopping the copy a bit. Things I think we want to convey:

- (most of) the settings still exist
- they've moved to their relevant top-level places
- you can search from the search bar (or Applications menu?)
- it's to make things more accessible for everyone

That's a lot, so we may want to pick and choose the most important things to focus on.

**Comment by cassidyjames** [comment]
Another sort of approach, focusing less on them "moving" and just being informative.

>**Looking for more settings?**
>Accessibility features can be found throughout System Settings. Check the relevant settings pages, or use the search bar from the All Settings screen.
